services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.prod
    environment:
      - NODE_ENV=production

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
