name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  API_ECR_REPOSITORY: regitrack-api
  NGINX_ECR_REPOSITORY: regitrack-nginx
  ECS_CLUSTER_NAME: regitrack-cluster
  API_ECS_SERVICE: regitrack-api-service
  NGINX_ECS_SERVICE: regitrack-nginx-service

jobs:
  # --- CI Job ---
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --force

      - name: Run linter
        run: pnpm lint

      - name: Run production build
        run: pnpm docker:prod:build

  # --- CD Job ---
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: build-and-test # This job depends on the CI job in this file
    # This condition ensures the deploy job ONLY runs on a push to the main branch,
    # not on pull requests.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push API image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$API_ECR_REPOSITORY:$IMAGE_TAG -f apps/api/Dockerfile.prod .
          docker push $ECR_REGISTRY/$API_ECR_REPOSITORY:$IMAGE_TAG

      - name: Build and push Nginx image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$NGINX_ECR_REPOSITORY:$IMAGE_TAG -f nginx/Dockerfile .
          docker push $ECR_REGISTRY/$NGINX_ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS services
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $API_ECS_SERVICE --force-new-deployment
          aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $NGINX_ECS_SERVICE --force-new-deployment
